export const DOCUMENT_UPLOAD_ACCEPTED_TYPES = ['image/jpeg', 'image/png', 'application/pdf']

export const DOCUMENT_UPLOAD_MAX_SIZE_BYTES = 20 * 1024 * 1024

export const DOCUMENT_UPLOAD_SERVER_MAX_DURATION_SECONDS = 90

export const DOCUMENT_UPLOAD_CLIENT_TIMEOUT_MS =
  (DOCUMENT_UPLOAD_SERVER_MAX_DURATION_SECONDS + 15) * 1000