services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-medv0/sami}:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: "0.0.0.0"
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_GENERATIVE_AI_API_KEY: ${GOOGLE_GENERATIVE_AI_API_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL:-}
    ports:
      - "3000:3000"
    networks:
      - sami
      - shared-network

networks:
  sami:
    driver: bridge
  shared-network:
    external: true
    name: shared-network
