-- Align medical_profiles table with application schema (adds sleep_hours and other profile fields)
BEGIN;

-- Preserve existing data while migrating to the new structure
ALTER TABLE "medical_profiles" RENAME TO "medical_profiles_old";

CREATE TABLE "medical_profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"age" integer NOT NULL,
	"gender" text NOT NULL,
	"height" integer NOT NULL,
	"weight" numeric(5, 2) NOT NULL,
	"systolic_pressure" integer NOT NULL,
	"diastolic_pressure" integer NOT NULL,
	"resting_heart_rate" integer NOT NULL,
	"health_objectives" text NOT NULL,
	"medical_conditions" text[],
	"medications" text[],
	"allergies" text[],
	"surgeries" text[],
	"family_history" text,
	"notes" text,
	"handgrip_strength" numeric(5, 2),
	"sit_to_stand_time" numeric(5, 2),
	"vo2_max" numeric(5, 2),
	"body_fat_percentage" numeric(5, 2),
	"co2_tolerance_test" numeric(5, 2),
	"latest_biomarkers" jsonb,
	"biomarkers_updated_at" timestamp,
	"sleep_hours" numeric(4, 1),
	"sleep_quality" integer,
	"sleep_issues" text,
	"time_in_bed" numeric(4, 1),
	"sleep_regularity" text,
	"daily_water_intake" numeric(4, 1),
	"stress_level" integer,
	"stress_management" text,
	"smoking_status" text,
	"smoking_details" text,
	"alcohol_consumption" text,
	"supplementation" text[],
	"current_diet" text,
	"exercise_activities" jsonb,
	"exercise_types" text[],
	"exercise_frequency" integer,
	"exercise_duration" integer,
	"exercise_intensity" text,
	"physical_limitations" text,
	"first_sunlight_exposure_time" text,
	"last_meal_time" text,
	"artificial_light_exposure_start" text,
	"artificial_light_exposure_end" text,
	"artificial_light_exposure_time" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "medical_profiles_user_id_unique" UNIQUE("user_id")
);

ALTER TABLE "medical_profiles" ADD CONSTRAINT "medical_profiles_user_id_users_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;

-- Best-effort migration of existing rows; fill mandatory fields with safe defaults when absent
-- Legacy rows lack several mandatory fields; we backfill with neutral placeholders
-- so the NOT NULL constraints remain valid until users update their profiles.
INSERT INTO "medical_profiles" (
	"id",
	"user_id",
	"age",
	"gender",
	"height",
	"weight",
	"systolic_pressure",
	"diastolic_pressure",
	"resting_heart_rate",
	"health_objectives",
	"medical_conditions",
	"medications",
	"allergies",
	"surgeries",
	"family_history",
	"notes",
	"handgrip_strength",
	"sit_to_stand_time",
	"vo2_max",
	"body_fat_percentage",
	"co2_tolerance_test",
	"latest_biomarkers",
	"biomarkers_updated_at",
	"sleep_hours",
	"sleep_quality",
	"sleep_issues",
	"time_in_bed",
	"sleep_regularity",
	"daily_water_intake",
	"stress_level",
	"stress_management",
	"smoking_status",
	"smoking_details",
	"alcohol_consumption",
	"supplementation",
	"current_diet",
	"exercise_activities",
	"exercise_types",
	"exercise_frequency",
	"exercise_duration",
	"exercise_intensity",
	"physical_limitations",
	"first_sunlight_exposure_time",
	"last_meal_time",
	"artificial_light_exposure_start",
	"artificial_light_exposure_end",
	"artificial_light_exposure_time",
	"created_at",
	"updated_at"
) SELECT
	"id",
	"user_id",
	30 AS "age", -- neutral fallback for legacy rows without age
	COALESCE("gender", 'outro') AS "gender",
	COALESCE("height", 170) AS "height",
	COALESCE("weight", 70)::numeric(5, 2) AS "weight",
	120 AS "systolic_pressure",
	80 AS "diastolic_pressure",
	70 AS "resting_heart_rate",
	'Não especificado' AS "health_objectives",
	NULL::text[] AS "medical_conditions",
	NULL::text[] AS "medications",
	NULL::text[] AS "allergies",
	NULL::text[] AS "surgeries",
	NULL::text AS "family_history",
	NULL::text AS "notes",
	NULL::numeric(5, 2) AS "handgrip_strength",
	NULL::numeric(5, 2) AS "sit_to_stand_time",
	NULL::numeric(5, 2) AS "vo2_max",
	NULL::numeric(5, 2) AS "body_fat_percentage",
	NULL::numeric(5, 2) AS "co2_tolerance_test",
	NULL::jsonb AS "latest_biomarkers",
	NULL::timestamp AS "biomarkers_updated_at",
	NULL::numeric(4, 1) AS "sleep_hours",
	NULL::integer AS "sleep_quality",
	NULL::text AS "sleep_issues",
	NULL::numeric(4, 1) AS "time_in_bed",
	NULL::text AS "sleep_regularity",
	NULL::numeric(4, 1) AS "daily_water_intake",
	NULL::integer AS "stress_level",
	NULL::text AS "stress_management",
	NULL::text AS "smoking_status",
	NULL::text AS "smoking_details",
	NULL::text AS "alcohol_consumption",
	NULL::text[] AS "supplementation",
	NULL::text AS "current_diet",
	NULL::jsonb AS "exercise_activities",
	NULL::text[] AS "exercise_types",
	NULL::integer AS "exercise_frequency",
	NULL::integer AS "exercise_duration",
	NULL::text AS "exercise_intensity",
	NULL::text AS "physical_limitations",
	NULL::text AS "first_sunlight_exposure_time",
	NULL::text AS "last_meal_time",
	NULL::text AS "artificial_light_exposure_start",
	NULL::text AS "artificial_light_exposure_end",
	NULL::text AS "artificial_light_exposure_time",
	COALESCE("created_at", now()) AS "created_at",
	COALESCE("updated_at", now()) AS "updated_at"
FROM "medical_profiles_old";

DROP TABLE "medical_profiles_old";

COMMIT;
